# This file was generated by GoReleaser. DO NOT EDIT.
class Amass < Formula
  desc "In-depth DNS Enumeration and Network Mapping"
  homepage "https://www.owasp.org/index.php/OWASP_Amass_Project"
  version "3.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/OWASP/Amass/releases/download/v3.1.3/amass_v3.1.3_macos_amd64.zip"
    sha256 "add6c1d566c3daf40d15798081531250a441d96449aaf8ac11880f3473c169a6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/OWASP/Amass/releases/download/v3.1.3/amass_v3.1.3_linux_amd64.zip"
      sha256 "005dbc8b3b74a60240904785b624aada25346211c21ccea0673f8edec470ca3c"
    end
  end

  def install
    bin.install "amass"
  end
end
