# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amass < Formula
  desc "In-depth Attack Surface Mapping and Asset Discovery"
  homepage "https://owasp.org/www-project-amass/"
  version "3.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OWASP/Amass/releases/download/v3.15.0/amass_macos_amd64.zip"
      sha256 "1f09e56d769522b36d90febb2dff426ec8ce6fdc3cb5cb8d1d673b937631125d"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OWASP/Amass/releases/download/v3.15.0/amass_macos_arm64.zip"
      sha256 "c1f508eaaa07cc0112c1f57838000d237b85abdb91f4ed6524f7490a2b1dd03d"

      def install
        bin.install "amass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/OWASP/Amass/releases/download/v3.15.0/amass_linux_amd64.zip"
      sha256 "e251a66c0d06fdd5431a2b8f381c1887166b6c6c7176d665d744f70c026875ea"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/OWASP/Amass/releases/download/v3.15.0/amass_linux_arm.zip"
      sha256 "fb43e573d3704acaaf13b7fb5fb4928f64b14502b026307697371c8976c09fbd"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OWASP/Amass/releases/download/v3.15.0/amass_linux_arm64.zip"
      sha256 "d8b2f0d0a6242799d179839fa3272346295e6c60fd3cff3b0b2ed634cea5a68b"

      def install
        bin.install "amass"
      end
    end
  end

  test do
    system "#{bin}/amass --version"
  end
end
